# yamllint disable rule:line-length
---
steps:

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: [
      'gsutil',
      'rsync',
      '-d',
      '-r',
      'static/',
      'gs://${_STATIC_BUCKET}'
    ]
